output = "dbmodels"
wipe = true
no-tests = true
add-enum-types = true
pkgname = "dbmodels"
add-global-variants = true

[psql]
dbname = "db1"
host = "localhost"
port = 5432
user = "postgres"
pass = "2022"
sslmode = "disable"